### PR TITLE
unix: use mtime.clock.os rather than a custom C stub

### PR DESCRIPTION
**Pull request by djs55**
mtime seems to support multiple Unix platforms, including macOS.

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
My motivation is to simplify the package -- I notice it uses some custom build magic.

I pinned `lwt#tracing` and this, and then built a Xen unikernel just to check that linking still worked and no unwanted C symbols crept in. Let me know if there are better tests to try!

**Comment by djs55** [comment]
I should say that I also compared the timestamps created via the old and new methods, subtracted them and observed

- normally they were within a few 1000 units of each other
- if I added a `Unix.sleep 1` between the calls, the delta became 1e9 + 1000 units

**Comment by talex5** [comment]
Looks good :-) There's a benchmark script in `test` if you want to check it didn't get any slower.

**Comment by djs55** [comment]
Running `make test` with master commit ce085a0e5d9e09c821f327dfff124de713f8ab73:
```
Tracing OFF
plain_lwt:off: 196.058989 ns/run
profile_lwt:off: 186.311007 ns/run
Tracing ON
plain_lwt:on: 27282.991171 ns/run
profile_lwt:on: 32697.789907 ns/run
...
Tracing OFF
plain_lwt:off: 189.981937 ns/run
profile_lwt:off: 184.218168 ns/run
Tracing ON
plain_lwt:on: 27358.646870 ns/run
profile_lwt:on: 32105.221033 ns/run
...
Tracing OFF
plain_lwt:off: 192.512989 ns/run
profile_lwt:off: 192.716122 ns/run
Tracing ON
plain_lwt:on: 28476.597071 ns/run
profile_lwt:on: 33739.892960 ns/run
```
and then with this branch:

```
Tracing OFF
plain_lwt:off: 189.944983 ns/run
profile_lwt:off: 184.937954 ns/run
Tracing ON
plain_lwt:on: 1071.403980 ns/run
profile_lwt:on: 1251.430988 ns/run
...
Tracing OFF
plain_lwt:off: 184.060812 ns/run
profile_lwt:off: 186.703205 ns/run
Tracing ON
plain_lwt:on: 1043.784857 ns/run
profile_lwt:on: 1286.970139 ns/run
...
Tracing OFF
plain_lwt:off: 192.410946 ns/run
profile_lwt:off: 194.653988 ns/run
Tracing ON
plain_lwt:on: 1113.276958 ns/run
profile_lwt:on: 1289.124966 ns/run
```
Am I misreading this or is the new code faster?

**Comment by talex5** [comment]
I wonder if we were missing a `-O3` somewhere before? A very nice speedup, if it still works!

**Comment by djs55** [comment]
It looks like the 2 implementations are different. The slow one does
```
host_get_clock_service()
clock_get_time()
mach_port_deallocate()
```
whereas the [fast one](https://github.com/dbuenzli/mtime/blob/master/src-os/mtime_clock_stubs.c) does
```
mach_absolute_time()
```
and then multiplies by a scaling factor which is constant for the machine. I found this [technical note](http://web.archive.org/web/20090901214152/http://developer.apple.com/mac/library/qa/qa2004/qa1398.html) describing the fast version. So I think the faster API explains the difference.

**Comment by talex5** [comment]
Ah, OK. Any idea why Travis is failing?

**Comment by djs55** [comment]
Looks like the old `mtime` API. I've pushed a constraint.

**Comment by talex5** [comment]
That's annoying:

```
  - mtime>=1.0.0 is not available because your system doesn't comply with ocaml-version >= "4.03.0".
```

For most libraries, dropping 4.02 doesn't matter, but mirage-profile is supposed to be something that everything can depend on.

I think the solution is to split it into multiple opam packages: the core stubs (that don't really need anything, but which everything else depends on) and the unix/xen implementations (which are only needed when you want to do some actual tracing and can have stricter requirements).

(this is something I've been meaning to do anyway)

**Comment by djs55** [comment]
Ah ok -- I can look at the split next. It might make sense to jbuilder it at the same time, since jbuilder seems particularly adept at handling multiple opam packages. The only tricky thing left is your pre-processor stuff but it turns out that `jbuilder` has support for that kind of module-level `#ifdef` stuff.

**Comment by djs55** [comment]
Current problem:
```
∗  installed mtime.1.0.0
∗  installed mirage-profile-unix.0.7.0
Done.
+make test
jbuilder runtest --dev
Error: External library "mtime.clock.os" not found.
-> required by "unix/jbuild (context default)"
```

**Comment by talex5** [comment]
I think it needs multiple OCaml targets for Travis:
- 4.02 should only build the main package (no tracing)
- 4.03 should also run the tests (and therefore use `Mtime_clock`, which doesn't appear to be available on 4.02).

**Comment by djs55** [comment]
A shiny new 4-case travis configuration now passes!

**Pull request merged**
